name: grupo-1-frontend
services:
  frontend:
    image: cleviobecerra/grupo-1-frontend:entrega-9
    ports:
      - "80:80"
  plantopia:
    image: cnicolas86/plantopia:1.2.1
    platform: linux/amd64
    container_name: plantopia-prod
    ports:
      - "4000:4000"
    env_file:
      - ./.env.productivo
    depends_on:
      - mysql
      - flyway
    networks:
      - plantopia-network

  mysql:
    image: mysql:8.0
    container_name: mysql-prod
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: PlantopiaDB
      MYSQL_USER: user_prod
      MYSQL_PASSWORD: password_prod
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - plantopia-network

  flyway:
    image: flyway/flyway:latest
    container_name: flyway-migrator
    depends_on:
      - mysql
    command: -X -url=jdbc:mysql://mysql:3306/PlantopiaDB -user=user_prod -password=password_prod -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./migrations:/flyway/sql  # Asegúrate de que esta ruta esté correcta
    networks:
      - plantopia-network
    restart: on-failure  # Reinicia Flyway si falla

networks:
  plantopia-network:
    driver: bridge

volumes:
  mysql-data: